### ISSUE TITLE
Missing htaccess?

### ISSUE THREAD

**Issue by peterbrinck** [berrnd/grocy#1]
Shouldn't there be a htaccess file?

The URL's are SEO friendly, but there's not htaccess to rewrite them

**Comment by berrnd** [comment]
Hi,

sorry for the late response - I personally don't use Apache, but nginx - the configuration is simple:
```
location / {
	try_files $uri /index.php;
}
```

grocy utilizes the Slim Framework, please refer to their documentation: https://www.slimframework.com/docs/start/web-servers.html

And I should maybe include a working example configuration for both Apache and nginx...
