### ISSUE TITLE
Idea: Products at which location

### ISSUE THREAD

**Issue by buster-one** [berrnd/grocy#10]
At first thank you for that management programm. Great work. :+1: 

What i would wish is a location overview. To see which products are at which location.

**Comment by berrnd** [comment]
Yes, that's already on my todo list (which I should probably add here as issues soon)...

Any idea/wish what would be best?
Maybe just a column on the stock overview page which can be filtered ... or an extended filter option (checkboxes or something) above the stock overview list ... or a dedicated page... (?)

**Comment by buster-one** [comment]
I would use it for our large freezer. There is a box for vegetables, meat etc. I need a location overview where i can see which products are available in the boxes.

In my case the best option would be a dedicated locationoverview page, where i can select as an example: Freezer_Meat_Box, Freezer_Vegetables_Box ... and see all products and amounts.

**Comment by buster-one** [comment]
Very nice. Thank you. :+1:
