### ISSUE TITLE
Stockoverview - Filter by location not selectable

### ISSUE THREAD

**Issue by buster-one** [berrnd/grocy#11]
On the demo site on the stockoverview page the dropdown "Filter by location" has no function. It is empty. Tested with several different browsers.

**Comment by berrnd** [comment]
Sorry, I only tested with Firefox 61 (current stable), can verify this with for example Firefox 62 (current Developer Edition) - will fix this shortly...

**Comment by berrnd** [comment]
Should now be fixed in v1.12.1...

**Comment by buster-one** [comment]
Thank you that you could solve it so quickly.
