### ISSUE TITLE
Login and Logout issue

### ISSUE THREAD

**Issue by buster-one** [berrnd/grocy#12]
I think there is something wrong with the login session cookies. I tested several browser.
On Firefox 61.0 i can login, but after i always on the login page again. I can as an example, go to the purchase page, but when i go to the stockoverview page i see the login page again. Some pages are available and some show the login page.

On my mobile device i can login with Brave, but i can't logout. anymore.

The cookies and cache are deleted several times!

**Comment by berrnd** [comment]
My private grocy installation I also access with Firefox 61 daily and haven't noticed this issue...
Have you tried without any plugins or other client-side things which may delete cookies or block something?

- The session cookie is set [here](https://github.com/berrnd/grocy/blob/778191fd11f3c75b74dc118e5adc533b5e3c2b21/controllers/LoginController.php#L30) and valid for 1 year, although the session id saved in the database is only valid for 30 days as done [here](https://github.com/berrnd/grocy/blob/778191fd11f3c75b74dc118e5adc533b5e3c2b21/services/SessionService.php#L42)
- It's never deleted client side, only when you logout the session id is invalidated in the database [here](https://github.com/berrnd/grocy/blob/778191fd11f3c75b74dc118e5adc533b5e3c2b21/services/SessionService.php#L51)

So I can only imagine that the cookie is deleted client side - have you checked if the cookie is still there when you get logged out?

Othere thing would to check the sessions in the database, table `sessions`.

**Comment by buster-one** [comment]
I tested several devices and browser without any customizations. All the same strange behavior. I don't think it is an client side issue.

**Comment by berrnd** [comment]
I enabled authentication on the English demo page, wich is running the latest released version 1.12.1 (both password and username is `admin`):
=> https://demo-en.grocy.info

Maybe you can test it there and let me know the steps to reproduce?

**Comment by buster-one** [comment]
On the demo page it works fine. :+1: 

Maybe it is an webserver issue? I will test this the next days.

**Comment by buster-one** [comment]
Sessions are fine in the database. Expires 2018-08-11 18:49:33.
Server Error Logs are empty. I already used another PHP Version 7.1... Same problem.

Meanwhile i think it is a cache problem. Some pages only show the login page. I set the config to german language. Some pages are still in english. Every page must individually complete reloaded to show in german. This is strange.

**Comment by berrnd** [comment]
Hm, yeah - really strange...

The used templating engine (Blade from Laravel) stores cached views in `data/viewcache`, is this directory writable and are there files created?

**Comment by buster-one** [comment]
`data/viewchache` is writeable. There are also some php files.

**Comment by berrnd** [comment]
Were you able to resolve this in the meantime or is there anything I could help with further on?

Just as a hint if you use windows and maybe want to use grocy only localy on one machine - there is now also [grocy-desktop](https://github.com/berrnd/grocy-desktop) which makes this possible without to have to manage a webserver...

**Comment by buster-one** [comment]
Unfortunately, no. But I'm sure it is a cache problem. At the moment I do not have the time to continue testing.

Maybe you can close as not reproducible? If there are any news a can open a new issue.

**Comment by berrnd** [comment]
Ok, will close this for now...
