### ISSUE TITLE
Minor UI issue

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#15]
When managing master data the scrollbar overlaps sligtly. 
 
![capture](https://user-images.githubusercontent.com/6298655/42737248-4e8a7a32-8871-11e8-9c13-3b6b5ad9631e.PNG)

**Comment by berrnd** [comment]
Must be in Chrome? I don't have this in Firefox...

**Comment by BlizzWave** [comment]
You are correct. Works fine in Firefox, but not in Chrome

**Comment by BlizzWave** [comment]
Just a little heads up. This issue is back on the pre-release

**Comment by berrnd** [comment]
Oh oh, that scrollbar...

For this issue it was just completely hidden as a workaround, in #90 it was added again with different CSS attributes ... still cannot reproduce this in Firefox stable and dev ... at time of closing #90 I also tested this ([or maybe it was you](https://github.com/grocy/grocy/issues/90#issuecomment-432334695)) in Chrome ... so will open #90 again to track this...

**Comment by berrnd** [comment]
I hope now finally https://github.com/grocy/grocy/commit/ca5df3b21729e91d7de166665f46c32af83bd849 did the trick - at least I can confirm this now for Firefox and Chrome stable...
