### ISSUE TITLE
Catchable fatal error: Argument 2 passed to Grocy::ExecuteDbStatement() must be an instance of string, string given, called in Grocy.php on line 23 and defined in Grocy.php on line 60

### ISSUE THREAD

**Issue by GaneshKandu** [berrnd/grocy#2]
Hi
Getting this error after login of new installed grocy

**Catchable fatal error**: Argument 2 passed to Grocy::ExecuteDbStatement() must be an instance of string, string given, called in **Grocy.php** on line 23 and defined in **Grocy.php** on line **60**

**Comment by GaneshKandu** [comment]
PHP version < 7.0

**Comment by berrnd** [comment]
Hello,

yeah - I didn't pay attention to make it < PHP 7.0 compatible ... I'll add this to README...
