### ISSUE TITLE
New setup shows a blank page

### ISSUE THREAD

**Issue by Drudoo** [berrnd/grocy#20]
I have tried using both docker with a lamp stack or my regular hosted webhost and both times i get a blank page when trying to connect to public/index.php

**Comment by berrnd** [comment]
What does the webserver error log say? Are you sure you use PHP 7.2 and SQLite extension is enabled?

**Comment by Drudoo** [comment]
I was sure i had php 7.2, but i tried a fresh docker with php7.2 for sure and this is the error i get:

` Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/services/DatabaseService.php:17 Stack trace: #0 /var/www/html/services/DatabaseService.php(17): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/services/DatabaseService.php(33): Grocy\Services\DatabaseService->GetDbConnectionRaw() #2 /var/www/html/controllers/BaseController.php(13): Grocy\Services\DatabaseService->GetDbConnection() #3 /var/www/html/controllers/LoginController.php(14): Grocy\Controllers\BaseController->__construct(Object(Slim\Container)) #4 /var/www/html/app.php(25): Grocy\Controllers\LoginController->__construct(Object(Slim\Container), 'grocy_session') #5 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container)) #6 /var/www/html/vendor/slim/slim/Slim/Container.php(123): Pimple\Container->offsetGet('LoginController...') #7 /var/www/html/vendor/slim/slim/Slim/Container.php(172): Slim\Container->get('LoginController...') #8 /var/www/html/routes.php(60): Slim in /var/www/html/services/DatabaseService.php on line 17`

**Comment by Drudoo** [comment]
This might have fixed the problem `chown -R www-data:www-data /var/www/html`

**Comment by berrnd** [comment]
Yes, the `/data `directory must be writable...

**Comment by warsix4** [comment]
I am having this same error, but the permissions are correct for the directories. Is therea nything else that may cause this? I'm running PHP 7.2 and SqLite 3.8.3

**Comment by warsix4** [comment]
I am having this same error, but the permissions are correct for the directories. Is therea nything else that may cause this? I'm running PHP 7.2 and SqLite 3.8.3

**Comment by berrnd** [comment]
Double check that your configured webserver root directory is `/public`...

What's the error message - as above about "unable to open database file" - that it can only be permissions or wrong paths...

**Comment by warsix4** [comment]
The sqlite PDO driver for some reason was not working in the VM I spun up. Running

`sudo apt install php7.2-sqlite` 

again was enough to solve the issue. Thanks. Great tool!
