### ISSUE TITLE
Feature Request: Adding family members to habit tracking

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#21]
Adding the feature to be able to choose who carried out a habit.
So you would need to add a "Family Members" tab to "Manage Master Data".

This could also be used elsewhere in Grocy to track who did something?

**Comment by berrnd** [comment]
I think the single fixed user (currently defined in `/data/config.php`) should maybe be replaced with a multi-user thing and then we could also use the same users for this...

**Comment by BlizzWave** [comment]
How would that work in embedded mode?

**Comment by BlizzWave** [comment]
Let's say you are running embedded mode. Then you want to log who did a habit/ chore. How will that be possible?

Just thinking out loud here.

**Comment by berrnd** [comment]
Thinking of just a dropdown were you can select any user / family member, maybe prefilled with the current logged on user, in embedded mode then not prefilled...

Just thought that family members then will also be users (maybe) and it gets confusing when there is only a single user for login defined in the config file instead...

**Comment by BlizzWave** [comment]
The drop down menu seems the best for me.
