### ISSUE TITLE
Feature Request: Price tracking for products 

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#22]
Adding a purchase price when purchasing products and display a graph of price over a set time period.

**Comment by berrnd** [comment]
The following ideas on this:

- To keep it simpel, no currency conversion handling, currency unit/symbol will be defined in `config.php`
- Price can be entered during purchase, must be entered per purchase quantity unit, last price will be prefilled
- For added products during inventory the last price will be used
- Last price and small line chart of price history is shown in the product card (right side in purchase/consume/etc.)

The above is already done - maybe you can test it [in the already updated English demo](https://demo-en.grocy.info/purchase?createdproduct=Cheese) and give me feedback if this is what you thought of or if you have any other suggestions regarding this. (?) :)

**Comment by BlizzWave** [comment]
COOOOL!!

I dont think there is any need to do any currency conversion as log as you can set the currency unit/ symbol in the config.
Maybe have the currency unit change depending on what language you use? (But needs a override option if you what to use something else).

My intial thoughts. Need to do more testing.

**Comment by berrnd** [comment]
I think I'll close this for now, the base tracking should work - better/more statistics still needed everywhere...
