### ISSUE TITLE
Feature Request: Appliance/ equipment user manual database

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#25]
A feature where you could upload a pdf manual for each appliance/ equipment in the household.
Maybe have a in-browser pdf viewer?

Not sure if this will slow down grocy.

**Comment by berrnd** [comment]
Should be possible ... not sure about which fields an "equipment-item" should have ... would be a kind of asset management thing I think...

Things for all your ideas! :)

**Comment by BlizzWave** [comment]
I was thinking a link on the left "Household Manuals" then it shows you all manuals in alphabetically order, an box where you search for equipment will also be handy. Then if you click a pdf  it will be shown in a in-browser pdf viewer.

A upload page in the master data section will also be needed.

**Comment by berrnd** [comment]
"One new feature a day keeps the doctor away" or something like that is that common saying ... or maybe I mix something up... :D

Now that we have a file upload API, did a quick mockup regarding this: Just like the recipes page, "equipment" on the left side, on the right side the instruction manual of the selected equipment item will be shown, when there is none, then the description of the item.

Is that what you thought of this?

https://demo-prerelease.grocy.info/equipment

**Comment by BlizzWave** [comment]
Yeah, just as simple as that. Really cool!

**Comment by berrnd** [comment]
I think this is ready now (when you find no bugs :D)...

Also added a little [WYSIWYG editor](https://github.com/summernote/summernote) for editing the equipment notes - is also used for recipes now.

The PDF is shown via default browser `<embed>`, works at least in latest Firefox...

**Comment by BlizzWave** [comment]
Very nice. I will try and "break" it. haha

The WYSIWYG editor is very nice. Can even embed pictures and videos!

**Comment by BlizzWave** [comment]
Can you move the view of the PDF as far up as possible so that we maximize the view?

![equipfix](https://user-images.githubusercontent.com/6298655/46422339-6ade9900-c734-11e8-8193-cb24c0016e7d.jpg)

**Comment by berrnd** [comment]
Ok, space around the embedded PDF is removed...

**Comment by berrnd** [comment]
Ah sorry, I think you meant not the space, but to move it more upwards on the right side ... will check that...

**Comment by BlizzWave** [comment]
Yes Bernd. Thats why I added the customized screenshot ;-)

**Comment by berrnd** [comment]
Didn't noticed that in the first look at your screenshot :) ... should now fit better ... a little problem is also the height of the embedded PDF, everyhting is repsonsive, so the PDF would be just as big as as the rest of the content, had fixed "800px" height there before ... also improved that now with some dynamic height changes with JS ... looks ok in my tries...

(Will remove the added footer in the demo in a minute that you can check it there without that...)

**Comment by BlizzWave** [comment]
Some weird scaling issue on my tablet.

![capture](https://user-images.githubusercontent.com/6298655/46429049-cd8c6080-c745-11e8-9ffc-4e3486b742ed.PNG)

**Comment by berrnd** [comment]
Think so, also removed the header for now in the demo...

**Comment by BlizzWave** [comment]
Yeah, it was the header. So everything looks good now.
