### ISSUE TITLE
'Slim Application Error': misuse of aliased aggregate best_before_date

### ISSUE THREAD

**Issue by TheQueasle** [berrnd/grocy#33]
While attempting to install grocy 1.16.0 on a fresh install on CentOS 7.5 with PHP versions 7.2 or 7.3, an error is  thrown with the title 'Slim Application Error'.

### Expected Result

Grocy webapp shows up.

### Actual Result

The following error message is thrown while navigating to the grocy web app

```
Slim Application Error

The application could not run because of the following error:
Details
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 misuse of aliased aggregate best_before_date
File: /var/www/grocy/services/DatabaseService.php
Line: 45
Trace

#0 /var/www/grocy/services/DatabaseService.php(45): PDO->exec('CREATE VIEW sto...')
#1 /var/www/grocy/services/DatabaseMigrationService.php(30): Grocy\Services\DatabaseService->ExecuteDbStatement('CREATE VIEW sto...')
#2 /var/www/grocy/services/DatabaseMigrationService.php(21): Grocy\Services\DatabaseMigrationService->ExecuteMigrationWhenNeeded(8, 'CREATE VIEW sto...')
#3 /var/www/grocy/controllers/LoginController.php(60): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 [internal function]: Grocy\Controllers\LoginController->Root(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/grocy/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/grocy/middleware/SessionAuthMiddleware.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/grocy/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/grocy/vendor/slim/slim/Slim/App.php(513): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/grocy/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/app.php(54): Slim\App->run()
#19 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#20 {main}
```

### Steps to reproduce the issue
Fresh install of CentOS 7.5
Install/enable Remi Repos for PHP 7.2 or 7.3
Install php-pdo (with respect to above versions)
Install grocy to /var/www/grocy
Navigate to webapp

### Information on your system
* grocy 1.16.0
* CentOS Linux release 7.5.1804 (Core)
* PHP 7.2 or PHP 7.3 from REMI repos
* Apache 2.4
* SELinux set to permissive
* Data directory owned by Apache user with read/write permissions

**Comment by BlizzWave** [comment]
Did you install php-sqlite3?
Also please double check that the data folder is writable by Apache.

**Comment by berrnd** [comment]
So seems to be a problem with the `CREATE VIEW` SQL command in [migration 8](https://github.com/berrnd/grocy/blob/master/migrations/0008.sql).

Cannot reproduce this, but the `ORDER BY` in the view is not necessary and also not valid SQL (overlooked this, as it threw no error so far, SQLite is somewhat forgiving at those things... :/).

Could you maybe please replace the file `migrations/0008.sql` with [the one from here](https://raw.githubusercontent.com/berrnd/grocy/fix-issue-33/migrations/0008.sql) and check if this fixes this? If yes, I have to find a way how to properly roll this out for both new and existing installations...

**Comment by TheQueasle** [comment]
I can try your suggestion tonight and get back to you. 

Thanks!

**Comment by TheQueasle** [comment]
@berrnd Was able to get to this sooner than planned.

Replacing `migrations/0008.sql` with the file located [here](https://raw.githubusercontent.com/berrnd/grocy/fix-issue-33/migrations/0008.sql) does seem to have solved the issue (tested against php7.2 and php7.3).

After replacing the file, the grocy login page loaded up and I was able to log in using the default username/password combo.

Let me know if you want/need any more information, and thanks for the fix!

**Comment by berrnd** [comment]
Thanks for testing this! Just strange that I cannot reproduce this with PHP 7.2 on Debian 9 and with PHP 7.2 on Windows 10 - anyway, an `ORDER BY` in a view is wrong, so that was the problem...
