### ISSUE TITLE
Issue: Batteries does not disappear in batteries overview page

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#34]
If you delete a battery from the admin master data -> batteries section it does not go away from the battery overview page. It just leaves a blank line with the old logged date.
Please have a look at the attached picture.

![battery issue](https://user-images.githubusercontent.com/6298655/43481497-60c91a22-9506-11e8-9692-6a930e46d9a8.PNG)

**Comment by berrnd** [comment]
Ok, but what should happen? Should we prevent deleting the battery? Or just hide on the overview page?
(Will be the same for products and habits.)

**Comment by BlizzWave** [comment]
I would assume that deleting the battery will remove everything logged about that specific battery?

Looks very weird with blank lines with logged lines in the overview. 
So hiding or deleting is the way to go.

**Comment by berrnd** [comment]
This is now indirectly resolved by https://github.com/berrnd/grocy/commit/e830805443048b50d553bbf2349ead3dcf55f976. Tracked charge cycles or habit executions will still not be deleted from the database for now when deleting the habit/battery. How to handle deleted master data in general is on open point for the future.

**Comment by goliath888** [comment]
I was experimenting with battery features and came here to post this problem. I cannot edit/delete a battery record even after removing the battery. I was making some test and now I have all this test-records in the batteries history.  @berrnd, Is it possible to remove them permanently?

**Comment by berrnd** [comment]
Please open separate issues for different topics, I've moved this to #1069.

Currently it's not possible to remove journal entries via the UI, but you can always edit the database manually with an SQLite editor of your choice. For the batteries journal it's the `battery_charge_cycles` table.

**Comment by goliath888** [comment]
I solve it as you say, just editing the data base. Simple and effective. Thanks
