### ISSUE TITLE
Issue: No place to actually set the desired charge cycle for batteries

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#35]
There is no place to actually set the desired charge cycle for batteries.

**Comment by berrnd** [comment]
This was already fixed in commit https://github.com/berrnd/grocy/commit/9e493430d8292b908f6739ddc7226966941e87ce and will be part of the next release.

**Comment by BlizzWave** [comment]
Argh! I knew I read about this in one of your commit comments
