### ISSUE TITLE
Issue: Minor GUI issue with "OK" button on certain pages

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#36]
When you populate all fields in habit tracking and battery tracking the "OK" button does not change color to green, it stays faded, but it works

**Comment by berrnd** [comment]
In habit/battery tracking I can only reproduce this when manually selecting from the dropdown by mouse. When searching/typing and pressing tab to jump to the next input it works.

Is this what you noticed?

**Comment by BlizzWave** [comment]
Thats correct
