### ISSUE TITLE
Quantity unit purchase Red

### ISSUE THREAD

**Issue by jasonkuehl** [berrnd/grocy#38]
![image](https://user-images.githubusercontent.com/9578513/43601620-9fbdd3e8-965b-11e8-9fb1-befe99872470.png)

For some reason Quantity unit purchase  and Quantity unit stock are red and im unable to change it at all.

**Comment by berrnd** [comment]
Have you added any quantity units (Manage master data/Quantity units)?

**Comment by jasonkuehl** [comment]
Yeah, I just saw it on the demo ago called Quantity units. All good, sorry about that.

**Comment by berrnd** [comment]
👍, no problem. :)
