### ISSUE TITLE
Issue: Another minor refresh issue

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#39]
The refresh of the overview pages are almost perfect Mr Bernd.
Please look at the attached screenshot.

![refresh](https://user-images.githubusercontent.com/6298655/43679118-d585f666-981f-11e8-9a5e-92d7c6943c3c.PNG)

**Comment by berrnd** [comment]
Ja - I already was guessing that you will notice this... :D

I think to make the whole page "dynamic" a kind of JavaScript frontend framework with data binding and stuff would be best, making every little thing manually produces a lot of maybe not so maintainable code ... but that's unfortunately not really my world ... but I will find a solution anytime soon... :)

**Comment by berrnd** [comment]
Absolutely not - as said already by mail, such "issues" and "requests" are more a kind of motiviation for me - and thanks for testing all the time! :)
