### ISSUE TITLE
Feature Request: Bigger amount buttons

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#44]
I have a tablet in my kitchen that shows Grocy 24/7. But I find it difficult to set amount with those tiny arrow buttons. (I dont want to show the on-screen keyboard) What do you think about making them a little bigger for a more touch friendly interface?

**Comment by berrnd** [comment]
These are just numeric inputs, so the up/down arrows are browser specific ... will check if they can be styled...

**Comment by BlizzWave** [comment]
Been searching for a solution myself to this. 
We are not the first ones to ask the questiong, hehe

Using something like this to the main css:

`input[type=number] {
    height: 30px;
}

input[type=number]:hover::-webkit-inner-spin-button {  
    width: 14px;
    height: 30px;
}
`

**Comment by berrnd** [comment]
I just replaced the default buttons with ones for this, will look like this:

![firefox_2018-09-08_12-03-50](https://user-images.githubusercontent.com/2161815/45252991-9782d900-b35f-11e8-90dc-ae1452c24559.png)
