### ISSUE TITLE
Issue: Flickering tooltips

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#51]
![test](https://user-images.githubusercontent.com/6298655/45038898-83d72a00-b062-11e8-9215-202a1dfd3637.gif)

**Comment by BlizzWave** [comment]
Found out that we need to add this:

`.tooltip {`
`        pointer-events: none;`
`}`

To grossy.css

**Comment by berrnd** [comment]
Thanks, will add this...

**Comment by BlizzWave** [comment]
Well after seems I was wrong. We need to have my intial solution here. 
Flickering on computer will just have to live with the tooltips staying until something else is clicked.

```css
.tooltip {
        pointer-events: none;
}
```

**Comment by berrnd** [comment]
The left over problem regarding tooltips will continue in #67.
