### ISSUE TITLE
Issue: Search keyword being retained

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#52]
If you search for something on the stock overview page it will retain the search keyword even if you change to another page. When you return to the stock overview page the search box will be blank, but its still showing the result of what you searched for.
To get it to remove the results you have to search for something new and then remove it (backspace).

The retain feature is actually nice, but would be nice if it would remember the keyword even if changing pages. 
Maybe also a "**Clear Search**" button?

![grocy_issue](https://user-images.githubusercontent.com/6298655/45115179-692eaf00-b14f-11e8-8782-5416662c4a17.gif)

**Comment by berrnd** [comment]
Hm, seems to be done automatically because I enabled ["stateSave" in DataTables](https://datatables.net/reference/option/stateSave) (saves the complete state of a table in local storage)...

Don't know if retaining the filter is good or not in general - could obviously simply be excluded as in [this example](https://datatables.net/reference/option/stateSaveParams#Example)...

**Comment by berrnd** [comment]
(Also applies for the location filter and all other pages where filtering of data tables is available...)

**Comment by BlizzWave** [comment]
Cool, I tried the example.
Now nothing is retained.

```js
var stockOverviewTable = $('#stock-overview-table').DataTable({
        'paginate': false,
        'order': [[3, 'asc']],
        'columnDefs': [
                { 'orderable': false, 'targets': 0 },
                { 'visible': false, 'targets': 4 }
        ],
        'language': JSON.parse(L('datatables_localization')),
        'scrollY': false,
        'colReorder': true,
        'stateSave': true,
        'stateSaveParams': function (settings, data) {
          data.search.search = "";
        }
});

```

**Comment by berrnd** [comment]
Thanks for trying - will add this just that way...
