### ISSUE TITLE
Feature Request: Isle Field

### ISSUE THREAD

**Issue by Toucan-Sam** [berrnd/grocy#55]
I'm not sure why this isn't a thing with any grocery apps, but I'd love to see an "isle" field attached to products. I'd think most people shop at the same stores the majority of the time.

If adding the isle of items meant you could then sort by isle number as a column you could make shopping trips much more efficient.

**Comment by Toucan-Sam** [comment]
Hello!

Yep. An easy way to sort all the items in your list into the sections of the store they're located in.

I think I'd personally prefer just isle numbers as opposed to actual categories though. 

As an example, baking and sauces are in the same isle, but if you were to automatically sort them, a whole bunch of things would be between B for baking and S for sauces.

I want to be able to sort the list so I can walk down isle one, up isle two etc etc one time each and get everything on my list in that isle.

Often bakeries or produce (fruits and vegetables) live in their own sections and not in isles so I'm not exactly site how to account for that. Maybe a "sorting" column with a field you can add any entries you like?

* Bakery
* Bakery
* Produce
* Isle 2
* Isle 5
* Isle 5
* Isle 6

On mobile at the moment but can mock up a thing for discussion in ms paint. :)

**Comment by berrnd** [comment]
I think I know what you mean... :)

So will add just a field attached to products as mentioned above and show this in the shopping list, every field in every table can be sorted and if you name them for example
01 Bakery
02 Produce
03 Isle 2
you can order them in the way they are located in the store.

**Comment by berrnd** [comment]
I added this now in version 1.19.0 - a field "product group" attached to products.

On the shopping list this field is used to group the items together - see the demo: https://demo-en.grocy.info/shoppinglist

Let me know if that works for you or if you have any other ideas regarding this. :)

**Comment by Toucan-Sam** [comment]
I like your implementation. Will be upgrading tonight. Thanks @berrnd !
