### ISSUE TITLE
Bug: Prompt to add known items in purchase page

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#56]
Please have a look at gif "video" underneath.

I manually type in "egg", then grocy suggests "Eggs". I click that, but it still uses what I typed in, "egg"

Funny thing, if you only type in "e" and then click on "Eggs" it works.

![grocy_issue](https://user-images.githubusercontent.com/6298655/45926611-36453300-bf25-11e8-9186-70a90f1805db.gif)

**Comment by BlizzWave** [comment]
This issue is still there

**Comment by berrnd** [comment]
The close from the commit was not intended...

I forked the [bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) component in the meanwhile to make a workaround for this, maybe you can also have a quick test for this in the [pre-release demo](https://demo-prerelease.grocy.info/purchase).

**Comment by berrnd** [comment]
Works now in all ways I tried, so will close this now...
