### ISSUE TITLE
Feature Request: Auto refresh (db watchdog)

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#59]
Is it possible to have some kind of auto refresh if the database changes (watchdog?) ?

I have a tablet in the kitchen that shows grocy 24/7. But sometimes I do updates to grocy on my laptop.
I have to manually refresh the tablet to see changes.

**Comment by berrnd** [comment]
In the current architecture I could only check every X minutes if something has changed and then reload the page (if idling for X minutes to not reload the page when the app is currently used)...

**Comment by BlizzWave** [comment]
Yeah, that would work.

**Comment by berrnd** [comment]
This is now ready in version 1.19.0 - I hardcoded for now that the database changed time is checked once a minute, when a change is detected, the current page is reloaded when there was no interaction for at least 50 seconds.

Hope this works for you. :)
