### ISSUE TITLE
Feature Request: Filter by colored bars in overview pages

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#60]
Make the colored bars in top of overviews pages clickable. 
Clicking one would only show whats stated inside the colored bar

**Comment by berrnd** [comment]
You can have a look on this in the new [pre-release demo](https://demo-prerelease.grocy.info) if you want... :)

**Comment by BlizzWave** [comment]
Spot on Mr Bernd!
Grocy is really getting good now.

**Comment by BlizzWave** [comment]
Small "bug". It remembers what you sort by. And you have to manually set it back to "All" if you switch to another page of grocy

**Comment by berrnd** [comment]
Thanks, a lot was done by your input - which is still my motivation... :)

... and except for the still missing "analysis" things, we put all the data in, but get no statistics out so far ... I'm still unsure how to do this - "programming" every single report would be a lot to do, using a dashboard tool (like [Grafana](https://grafana.com/) for example which I personally love for home automation things a lot) is maybe too difficult for the average user...

(Sorry for the off-topic here.)

**Comment by berrnd** [comment]
> Small "bug". It remembers what you sort by. And you have to manually set it back to "All" if you switch to another page of grocy

Hm, thought this was already fixed by (filtering form the dropdown is internally also just a normal search) https://github.com/berrnd/grocy/issues/52#issuecomment-418878056 - but I will have a look...

**Comment by berrnd** [comment]
> Do we need to think of having a simple forum for discussions or throwing out ideas?

I think for now that's ok here - maybe a new lable "discussion" or so when this get's more...
