### ISSUE TITLE
Bug: Showing below minimum in overview pages will not show item that is not in stock anymore

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#69]
A little bug, when you click the colored bars to filter below minimum it will not show the item that has a stock level of 0. (Of course we cant consume below 0).

![grocy_issue4](https://user-images.githubusercontent.com/6298655/46145710-47fa4380-c261-11e8-86d2-6425037973ef.gif)

I have to go into the shopping list to find it.

![grocy_issue5](https://user-images.githubusercontent.com/6298655/46145884-b3441580-c261-11e8-8c15-8ef5c9f7d7de.gif)

**Comment by BlizzWave** [comment]
Your fix gave us another issue.

Says "6 products expiring within the next 5 days"
There is actually just two.


![grocy](https://user-images.githubusercontent.com/6298655/46261901-5c0ca200-c4fa-11e8-9e45-fa43614dbb95.PNG)

**Comment by BlizzWave** [comment]
Just found another weird one here. 
A product needs to be expired for two days before it goes into the "# products are already expired".
It will go into the "# products expire within the next 5 days" group even though its expired.

![capture](https://user-images.githubusercontent.com/6298655/46629524-6e618e00-cb41-11e8-83e4-73e8582172aa.JPG)

**Comment by berrnd** [comment]
Internally there is always also a time, even when there is only a date displayed (mainly because SQLite has no date only data type) - so that's maybe part of the problem...

=> Tracking this in #87
