### ISSUE TITLE
Bug: Deleting products thats in stock.

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#81]
Theres a weird bug where if you delete a product that you have in stock the line becomes blank, but the amount still stays. 
So if you want to delete a product the stock level of that product has to be 0.
Similar to this old issue: #34 

This happened to me last night, only way I could fix it was to manually open the DB file and edit it.

![line blank](https://user-images.githubusercontent.com/6298655/46359327-4ec1f580-c669-11e8-904e-e6241e703793.JPG)

**Comment by berrnd** [comment]
Ok, so added that deleting of products is not possible to prevent this for now...
