### ISSUE TITLE
Responsive design - navbar overlapping content

### ISSUE THREAD

**Issue by d-Rickyy-b** [berrnd/grocy#9]
Since (at least) v1.8.0 the navbar is overlapping the content at certain resolutions.
I uploaded a video/gif of it [here](https://imgur.com/KDpNMQQ).

You can test it for yourself on your [demo page](https://demo-en.grocy.info/stockoverview), while using the dev tools of your browser.
___
Not sure if you'd prefer another issue for that, but the big `no-real-button`s on the main site are too big for mobile screens, so that the page becomes horizontally scrollable and the hamburger menu button is out of view when opening the page

**Comment by berrnd** [comment]
Thanks for finding that. :)

CSS is not so my thing, but I tried to improve the page-layout/responsiveness in version 1.10.0 (just released, demo is already updated) a little bit...
