### ISSUE TITLE
Feature Request: Change default item location behavior

### ISSUE THREAD

**Issue by Toucan-Sam** [berrnd/grocy#92]
Zero urgency on this and maybe even no change required. More of a discussion point.

Currently when you locations, the default becomes the first one alphabetically. This makes sense from a usability point where it's a required field (?) and so can't be empty.

My locations that currently exist are...
Bathroom
Fridge
Freezer
Pantry

So when my partner adds things to the list (who is not as technical) her default option is to add things to the Bathroom stock. Same could be said for the demo site where the default location will be "Candy Cupboard". 😄 

Now I could probably change this to "Medicine Cabinet" for alphabetical reasons and solve the issue, but it might be nice to have a change of behavior and either...
A) Be able to change the default selection
B) Set the field as blank and require a choice before saving the item (this makes sense to me, and not overly burdensome since it's a one time thing on creation)

What do you think? Leaving it alone is a perfectly reasonable answer. 😄

**Comment by berrnd** [comment]
Both sounds logic to me.

Point A (define one location as default) is what most normal/professional ERP systems do, I would say.

Point B is how other optional fields behave currently (ok, the location field is not optional for products...).
=> Will add it like this, if no one is against it.

**Comment by Toucan-Sam** [comment]
Optionally a toggle in settings for behavior could work?
Use default location <-> Require manual location on item creation

I'm sure there are arguments on both sides and many people would prefer to have the item added and fix it's location later.

**Comment by berrnd** [comment]
I added [a dedicated page](https://demo-prerelease.grocy.info/productpresets) to define the presets for new products (linked on the products list page). Including that you can leave the preset empty, which means you have to select it while creating a product. I think this should cover all needs regarding this.
