### ISSUE TITLE
Bug: Can't edit an item in Inventory if image is not set

### ISSUE THREAD

**Issue by Aerex** [berrnd/grocy#95]
First, I would like to say that this is a really cool service. I hope to contribute to the repository. I have some ideas on creating a client companion app to the service. 

In regards to the issue, I can't seem to select an item in the Inventory if the item in question doesn't have an image defined. I am not sure if this is by design but if it is perhaps a generic image or the image be a required field.

**Comment by berrnd** [comment]
> First, I would like to say that this is a really cool service. I hope to contribute to the repository. I have some ideas on creating a client companion app to the service.

Thanks! Looking forward to any ideas/contributions... :)

Do you mean that you cannot select a product on the [inventory page](https://demo-prerelease.grocy.info/inventory) which doesn't have an image or that you cannot edit such a product on the [products list page](https://demo-prerelease.grocy.info/products)?

Tried both and found no issue...

**Comment by BlizzWave** [comment]
This is per design. The edit is only available if there's a picture of the item. Maybe change the behavior to show product card regardless if there's a picture or not. In the product card you already show the picture? 

And just get the rid of the "picture of products"

**Comment by berrnd** [comment]
Ok, now I understand - already wanted to replace the product-picture-popup with a general popup of the product card (#93), can of course also add a link to the product edit page in the card...

**Comment by berrnd** [comment]
So I think I'll close this, will be tracked in #93.

**Comment by Aerex** [comment]
> Do you mean that you cannot select a product on the [inventory page](https://demo-prerelease.grocy.info/inventory) which doesn't have an image or that you cannot edit such a product on the [products list page](https://demo-prerelease.grocy.info/products)?

The latter.

> This is per design. The edit is only available if there's a picture of the item. Maybe change the behavior to show product card regardless if there's a picture or not. In the product card you already show the picture?

Alright I will take note of that. Thanks

**Comment by berrnd** [comment]
But on the [products list page](https://demo-prerelease.grocy.info/products) there is a edit button per line (in the first column). (?).

So this affects the [stock overview page](https://demo-prerelease.grocy.info/stockoverview) only, I think...
